export const faker = [
  {
    theme: 'Airline',
    value: [
      'aircraftType',
      'airline',
      'airplane',
      'airport',
      'flightNumber',
      'recordLocator',
      'seat',
    ],
  },
  {
    theme: 'Animal',
    value: [
      'bear',
      'bird',
      'cat',
      'cetacean',
      'cow',
      'crocodilia',
      'dog',
      'fish',
      'horse',
      'insect',
      'lion',
      'rabbit',
      'rodent',
      'snake',
      'type',
    ],
  },
  {
    theme: 'Color',
    value: [
      'cmyk',
      'colorByCSSColorSpace',
      'cssSupportedFunction',
      'cssSupportedSpace',
      'hsl',
      'human',
      'hwb',
      'lab',
      'lch',
      'rgb',
      'space',
    ],
  },
  {
    theme: 'Commerce',
    value: [
      'department',
      'price',
      'product',
      'productAdjective',
      'productDescription',
      'productMaterial',
      'productName',
    ],
  },
  {
    theme: 'Company',
    value: [
      'buzzAdjective',
      'buzzNoun',
      'buzzPhrase',
      'buzzVerb',
      'catchPhrase',
      'catchPhraseAdjective',
      'catchPhraseDescriptor',
      'catchPhraseNoun',
      'name',
    ],
  },
  {
    theme: 'Database',
    value: ['collation', 'column', 'engine', 'mongodbObjectId', 'type'],
  },
  {
    theme: 'Date',
    value: [
      'anytime',
      'between',
      'betweens',
      'birthdate',
      'future',
      'month',
      'past',
      'recent',
      'soon',
      'weekday',
    ],
  },
  {
    theme: 'Finance',
    value: [
      'accountName',
      'accountNumber',
      'amount',
      'bic',
      'bitcoinAddress',
      'creditCardCVV',
      'creditCardIssuer',
      'creditCardNumber',
      'currency',
      'currencyCode',
      'currencyName',
      'currencySymbol',
      'ethereumAddress',
      'iban',
      'litecoinAddress',
      'maskedNumber',
      'pin',
      'routingNumber',
      'transactionDescription',
      'transactionType',
    ],
  },
  {
    theme: 'Hacker',
    value: ['abbreviation', 'adjective', 'ingverb', 'noun', 'phrase', 'verb'],
  },
  {
    theme: 'Helpers',
    value: [
      'arrayElement',
      'arrayElements',
      'enumValue',
      'fake',
      'fromRegExp',
      'maybe',
      'multiple',
      'mustache',
      'objectEntry',
      'objectKey',
      'objectValue',
      'rangeToNumber',
      'regexpStyleStringParse',
      'replaceCreditCardSymbols',
      'replaceSymbolWithNumber',
      'replaceSymbols',
      'shuffle',
      'slugify',
      'uniqueArray',
      'weightedArrayElement',
    ],
  },
  {
    theme: 'Image',
    value: [
      'avatar',
      'avatarGitHub',
      'avatarLegacy',
      'dataUri',
      'url',
      'urlLoremFlickr',
      'urlPicsumPhotos',
      'urlPlaceholder',
    ],
  },
  {
    theme: 'Internet',
    value: [
      'avatar',
      'color',
      'displayName',
      'domainName',
      'domainSuffix',
      'domainWord',
      'email',
      'emoji',
      'exampleEmail',
      'httpMethod',
      'httpStatusCode',
      'ip',
      'ipv4',
      'ipv6',
      'mac',
      'password',
      'port',
      'protocol',
      'url',
      'userAgent',
      'userName',
    ],
  },
  {
    theme: 'Location',
    value: [
      'buildingNumber',
      'cardinalDirection',
      'city',
      'country',
      'countryCode',
      'county',
      'direction',
      'latitude',
      'longitude',
      'nearbyGPSCoordinate',
      'ordinalDirection',
      'secondaryAddress',
      'state',
      'street',
      'streetAddress',
      'timeZone',
      'zipCode',
    ],
  },
  {
    theme: 'Lorem',
    value: [
      'lines',
      'paragraph',
      'paragraphs',
      'sentence',
      'sentences',
      'slug',
      'text',
      'word',
      'words',
    ],
  },
  {
    theme: 'Music',
    value: ['genre', 'songName'],
  },
  {
    theme: 'Number',
    value: ['bigint', 'binary', 'float', 'hex', 'int', 'octal'],
  },
  {
    theme: 'Person',
    value: [
      'bio',
      'firstName',
      'fullName',
      'gender',
      'jobArea',
      'jobDescriptor',
      'jobTitle',
      'jobType',
      'lastName',
      'middleName',
      'prefix',
      'sex',
      'sexType',
      'suffix',
      'zodiacSign',
    ],
  },
  {
    theme: 'Phone',
    value: ['imei', 'number'],
  },
  {
    theme: 'Science',
    value: ['chemicalElement', 'unit'],
  },
  {
    theme: 'String',
    value: [
      'alpha',
      'alphanumeric',
      'binary',
      'fromCharacters',
      'hexadecimal',
      'nanoid',
      'numeric',
      'octal',
      'sample',
      'symbol',
      'uuid',
    ],
  },
  {
    theme: 'System',
    value: [
      'commonFileExt',
      'commonFileName',
      'commonFileType',
      'cron',
      'directoryPath',
      'fileExt',
      'fileName',
      'filePath',
      'fileType',
      'mimeType',
      'networkInterface',
      'semver',
    ],
  },
  {
    theme: 'Vehicle',
    value: ['bicycle', 'color', 'fuel', 'manufacturer', 'model', 'type', 'vehicle', 'vin', 'vrm'],
  },
  {
    theme: 'Word',
    value: [
      'adjective',
      'adverb',
      'conjunction',
      'interjection',
      'noun',
      'preposition',
      'sample',
      'verb',
      'words',
    ],
  },
];
